Repository ssitvit/Games-and-Go, pull requests merged in 2022-10, with the labels that each got.

#22 Update README.md
  README.md
Labels: hacktoberfest-accepted

#21 99 game added
  Contributors.md
  package-lock.json
  src/Games/Ninetynine/ninetynine.css
  src/Games/Ninetynine/ninetynine.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: hacktoberfest, hacktoberfest-accepted

#23 Memory game added
  src/Games/Memory/memory.css
  src/Games/Memory/memory.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: hacktoberfest
