Repository ssitvit/Games-and-Go, pull requests merged in 2023-07, with the labels that each got.

#632 added planet defense game
  src/Games/Planet_Defense/README.md
  src/Games/Planet_Defense/index.html
  src/Games/Planet_Defense/script.js
  src/Games/Planet_Defense/space.jpg
  src/Games/Planet_Defense/style.css
Labels: hacktoberfest, gssoc23, level2

#631 added_TypingMaster
  package.json
  src/Games/typingMaster/paragraphs.jsx
  src/Games/typingMaster/typing.css
  src/Games/typingMaster/typing.jsx
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: hacktoberfest, gssoc23, level2

#678 Dark mode button is added
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/Homepage.js
  yarn.lock
Labels: gssoc23, level1

#730 Egg Catch Game Added
  src/Games/Egg_Catch_Game/egg_catch.py
Labels: gssoc23, level1

#723 snake game
  src/Games/snake-game/index.html
  src/Games/snake-game/snake.css
  src/Games/snake-game/snake.js
Labels: gssoc23, level2

#702 [GSSoC'23] Added Alphabet Game Project
  Contributors.md
  src/Games/Alphabet_Game/Alphabet.css
  src/Games/Alphabet_Game/Alphabet.js
  src/Games/Alphabet_Game/README.md
  src/Games/Alphabet_Game/images/apple.png
  src/Games/Alphabet_Game/images/ball.png
  src/Games/Alphabet_Game/images/cat.png
  src/Games/Alphabet_Game/images/dog.png
  src/Games/Alphabet_Game/images/elephant.png
  src/Games/Alphabet_Game/images/fish.png
  src/Games/Alphabet_Game/images/fox.png
  src/Games/Alphabet_Game/images/grass.png
  src/Games/Alphabet_Game/images/hat.png
  src/Games/Alphabet_Game/images/insect.png
  src/Games/Alphabet_Game/images/jar.png
  src/Games/Alphabet_Game/images/kite.png
  src/Games/Alphabet_Game/images/lamp.png
  src/Games/Alphabet_Game/images/monkey.png
  src/Games/Alphabet_Game/images/nose.png
  src/Games/Alphabet_Game/images/ocean.png
  src/Games/Alphabet_Game/images/parrot.png
  src/Games/Alphabet_Game/images/queen.png
  src/Games/Alphabet_Game/images/rat.png
  src/Games/Alphabet_Game/images/sun.png
  src/Games/Alphabet_Game/images/tap.png
  src/Games/Alphabet_Game/images/umbrella.png
  src/Games/Alphabet_Game/images/violin.png
  src/Games/Alphabet_Game/images/water.png
  src/Games/Alphabet_Game/images/yellow.png
  src/Games/Alphabet_Game/images/zebra.png
  src/Games/Alphabet_Game/sounds/a.mp3
  src/Games/Alphabet_Game/sounds/b.mp3
  src/Games/Alphabet_Game/sounds/c.mp3
  src/Games/Alphabet_Game/sounds/d.mp3
  src/Games/Alphabet_Game/sounds/e.mp3
  src/Games/Alphabet_Game/sounds/f.mp3
  src/Games/Alphabet_Game/sounds/g.mp3
  src/Games/Alphabet_Game/sounds/h.mp3
  src/Games/Alphabet_Game/sounds/i.mp3
  src/Games/Alphabet_Game/sounds/j.mp3
  src/Games/Alphabet_Game/sounds/k.mp3
  src/Games/Alphabet_Game/sounds/l.mp3
  src/Games/Alphabet_Game/sounds/m.mp3
  src/Games/Alphabet_Game/sounds/n.mp3
  src/Games/Alphabet_Game/sounds/o.mp3
  src/Games/Alphabet_Game/sounds/p.mp3
  src/Games/Alphabet_Game/sounds/q.mp3
  src/Games/Alphabet_Game/sounds/r.mp3
  src/Games/Alphabet_Game/sounds/s.mp3
  src/Games/Alphabet_Game/sounds/t.mp3
  src/Games/Alphabet_Game/sounds/u.mp3
  src/Games/Alphabet_Game/sounds/v.mp3
  src/Games/Alphabet_Game/sounds/w.mp3
  src/Games/Alphabet_Game/sounds/x.mp3
  src/Games/Alphabet_Game/sounds/y.mp3
  src/Games/Alphabet_Game/sounds/z.mp3
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level1

#759 Dragon Dino Game added.
  src/Games/DragonDinoGame/Game.jsx
  src/Games/DragonDinoGame/images/bg.png
  src/Games/DragonDinoGame/images/dino.png
  src/Games/DragonDinoGame/images/dragon.png
  src/Games/DragonDinoGame/images/game.mp3
  src/Games/DragonDinoGame/images/gameover.mp3
  src/Games/DragonDinoGame/images/index.html
  src/Games/DragonDinoGame/images/music.mp3
  src/Games/DragonDinoGame/images/view.png
  src/Games/DragonDinoGame/style.css
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: hacktoberfest, gssoc23, level1

#755 Resolved overlapping changes and changed some styling
  package-lock.json
  package.json
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
  yarn.lock
Labels: gssoc23, level1

#665 added tower block game
  src/Games/Tower_Blocks/README.md
  src/Games/Tower_Blocks/index.html
  src/Games/Tower_Blocks/script.js
  src/Games/Tower_Blocks/style.css
Labels: gssoc23, level1

#712 Error Page added
  src/ErrorPage/ErrorPage.css
  src/ErrorPage/ErrorPage.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level1

#780 [Docs] Add direct link for code of conduct
  README.md
Labels: gssoc23, level1

#778 [FIX]: COPYRIGHT NOT VISIBLE ON LIGHT MODE 🛠
  src/Homepage/Homepage/DarkModeToggle.js
Labels: gssoc23, level1

#772 changed main heading of tic tac toe game
  src/Homepage/Data/data.js
Labels: gssoc23, level1

#771 Added the Floating Particles in Background
  src/Homepage/Homepage/Homepage.js
  src/Homepage/Homepage/particles.css
Labels: gssoc23, level1

#788 search bar updated #753 {video attached}
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
Labels: gssoc23, level1

#787 handled Game on in dark and light mode
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/Homepage.css
  yarn.lock
Labels: gssoc23, level2

#770 Added Pong Game javascript
  src/Games/Pong_Game/game.html
  src/Games/Pong_Game/index.html
  src/Games/Pong_Game/script.js
  src/Games/Pong_Game/style.css
  src/Games/Pong_Game/winner.html
  src/Homepage/Data/data.js
Labels: gssoc23, level2

#791 Added a clean footer
  package-lock.json
  package.json
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
  src/Homepage/Homepage/github.png
  src/Homepage/Homepage/instagram.png
  yarn.lock
Labels: bug, gssoc23, level1

#827 Fixed the navbar with color
  src/Homepage/Homepage/Navbar.css
Labels: gssoc23, level1

#804 Add Reunion Game
  src/Games/Reunion/README.md
  src/Games/Reunion/game.js
  src/Games/Reunion/index.html
  src/Games/Reunion/puzzle.js
Labels: gssoc23, level2

#859 Falling Ball Game
  package-lock.json
  src/Games/FallingBall/App.js
  src/Games/FallingBall/index.css
  src/Games/FallingBall/index.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: gssoc23, level1

#858 Added Play button
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
  src/Homepage/Homepage/Play.js
Labels: gssoc23, level1

#856 Update auto-comment.yml
  .github/workflows/auto-comment.yml
Labels: gssoc23, level1

#853 Adding a Guessing number Game
  README.md
  src/Games/guessing number/Readme.md
  src/Games/guessing number/guess.html
  src/Games/guessing number/script.js
  src/Games/guessing number/styles.css
Labels: gssoc23, level1

#845 'Games' Description Alignment Correction
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#867 Added Shoot The Target Game
  src/Games/ShootTheTarget/README.md
  src/Games/ShootTheTarget/index.html
  src/Games/ShootTheTarget/style.css
Labels: gssoc23, level1

#833 add back button
  package-lock.json
  package.json
  public/index.html
  src/Homepage/Homepage/Navbar.css
  src/Homepage/Homepage/Navbar.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: gssoc23, level2

#832 updated homepage about
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#857 Wordle-OG Project added in the Games folder
  src/Games/Wordle-OG/wordle/.gitignore
  src/Games/Wordle-OG/wordle/README.md
  src/Games/Wordle-OG/wordle/package-lock.json
  src/Games/Wordle-OG/wordle/package.json
  src/Games/Wordle-OG/wordle/public/favicon.ico
  src/Games/Wordle-OG/wordle/public/index.html
  src/Games/Wordle-OG/wordle/public/logo192.png
  src/Games/Wordle-OG/wordle/public/logo512.png
  src/Games/Wordle-OG/wordle/public/manifest.json
  src/Games/Wordle-OG/wordle/public/robots.txt
  src/Games/Wordle-OG/wordle/src/App.css
  src/Games/Wordle-OG/wordle/src/App.js
  src/Games/Wordle-OG/wordle/src/Words.js
  src/Games/Wordle-OG/wordle/src/components/Board.js
  src/Games/Wordle-OG/wordle/src/components/GameOver.js
  src/Games/Wordle-OG/wordle/src/components/Key.js
  src/Games/Wordle-OG/wordle/src/components/Keyboard.js
  src/Games/Wordle-OG/wordle/src/components/Letter.js
  src/Games/Wordle-OG/wordle/src/index.js
  src/Games/Wordle-OG/wordle/src/reportWebVitals.js
  src/Games/Wordle-OG/wordle/src/wordle-bank.txt
Labels: gssoc23, level1

#844 fixed social icons in darkmode
  public/index.html
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
Labels: gssoc23, level1

#872 added new 2048 game
  src/Games/2048_new_version/public/favicon.svg
  src/Games/2048_new_version/public/index.html
  src/Games/2048_new_version/public/logo192.png
  src/Games/2048_new_version/public/logo512.png
  src/Games/2048_new_version/public/manifest.json
  src/Games/2048_new_version/public/robots.txt
  src/Games/2048_new_version/src/assets/img/1024.gif
  src/Games/2048_new_version/src/assets/img/128.gif
  src/Games/2048_new_version/src/assets/img/16.gif
  src/Games/2048_new_version/src/assets/img/2.gif
  src/Games/2048_new_version/src/assets/img/2048.gif
  src/Games/2048_new_version/src/assets/img/256.gif
  src/Games/2048_new_version/src/assets/img/32.gif
  src/Games/2048_new_version/src/assets/img/4.gif
  src/Games/2048_new_version/src/assets/img/512.gif
  src/Games/2048_new_version/src/assets/img/64.gif
  src/Games/2048_new_version/src/assets/img/8.gif
  src/Games/2048_new_version/src/assets/img/game-over.gif
  src/Games/2048_new_version/src/assets/img/try-again.gif
  src/Games/2048_new_version/src/clear-sans.ttf
  src/Games/2048_new_version/src/components/Board.jsx
  src/Games/2048_new_version/src/components/Cell.jsx
  src/Games/2048_new_version/src/components/GameOverlay.jsx
  src/Games/2048_new_version/src/components/Tile.jsx
  src/Games/2048_new_version/src/helper/index.js
  src/Games/2048_new_version/src/hooks/useEvent.js
  src/Games/2048_new_version/src/index.js
  src/Games/2048_new_version/src/main.scss
  src/Games/2048_new_version/src/styles.scss
Labels: gssoc23, level1

#869 All files required are added
  src/Games/MemoryGame/.gitignore
  src/Games/MemoryGame/LICENSE
  src/Games/MemoryGame/README.md
  src/Games/MemoryGame/package-lock.json
  src/Games/MemoryGame/package.json
  src/Games/MemoryGame/public/assets/images/bootstrap.png
  src/Games/MemoryGame/public/assets/images/css.png
  src/Games/MemoryGame/public/assets/images/electron.png
  src/Games/MemoryGame/public/assets/images/firebase.png
  src/Games/MemoryGame/public/assets/images/html.png
  src/Games/MemoryGame/public/assets/images/javascript.png
  src/Games/MemoryGame/public/assets/images/jquery.png
  src/Games/MemoryGame/public/assets/images/mongo.png
  src/Games/MemoryGame/public/assets/images/node.png
  src/Games/MemoryGame/public/assets/images/react.png
  src/Games/MemoryGame/public/favicon.ico
  src/Games/MemoryGame/public/icon.png
  src/Games/MemoryGame/public/index.html
  src/Games/MemoryGame/public/manifest.json
  src/Games/MemoryGame/public/robots.txt
  src/Games/MemoryGame/src/App.js
  src/Games/MemoryGame/src/App.test.js
  src/Games/MemoryGame/src/components/CardElement.js
  src/Games/MemoryGame/src/components/GameBoard.js
  src/Games/MemoryGame/src/components/GameOver.js
  src/Games/MemoryGame/src/game/game.js
  src/Games/MemoryGame/src/index.css
  src/Games/MemoryGame/src/index.js
  src/Games/MemoryGame/src/reportWebVitals.js
  src/Games/MemoryGame/src/serviceWorker.js
  src/Games/MemoryGame/src/setupTests.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level1

#824 About Section Alignment
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level2

#818 #762 New game added
  src/Games/MindGame_2048/.gitignore
  src/Games/MindGame_2048/README.md
  src/Games/MindGame_2048/package-lock.json
  src/Games/MindGame_2048/package.json
  src/Games/MindGame_2048/public/favicon.ico
  src/Games/MindGame_2048/public/index.html
  src/Games/MindGame_2048/public/robots.txt
  src/Games/MindGame_2048/src/components/cell.jsx
  src/Games/MindGame_2048/src/components/endGame.jsx
  src/Games/MindGame_2048/src/components/mainBoard.jsx
  src/Games/MindGame_2048/src/components/tileView.jsx
  src/Games/MindGame_2048/src/index.js
  src/Games/MindGame_2048/src/styles/styles.css
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level1

#600 Memory Card Game
  src/Games/Memory Card Game/dog.png
  src/Games/Memory Card Game/doll.png
  src/Games/Memory Card Game/duck.png
  src/Games/Memory Card Game/fish-color.png
  src/Games/Memory Card Game/flames.png
  src/Games/Memory Card Game/index.html
  src/Games/Memory Card Game/intro
  src/Games/Memory Card Game/logic.js
  src/Games/Memory Card Game/pork.png
  src/Games/Memory Card Game/style.css
  src/Games/Memory Card Game/teddy-bear-brown.png
  src/Games/Memory Card Game/traffic-light.png
Labels: gssoc23, level1

#849 fixed styling of scroll to top button
  package-lock.json
  src/Homepage/Homepage/GoToTop.js
  yarn.lock
Labels: gssoc23, level1

#888 fix : Update UI Issues in Some Games
  src/Games/BattleShip/App.css
  src/Games/Tictactoe/tictactoe.js
Labels: gssoc23, level1

#887 darkmode button properly aligned
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/MusicButton.js
Labels: gssoc23, level1

#885 changed the border radius correction
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#891 back to top button corrected #767
  src/Homepage/Homepage/GoToTop.js
Labels: gssoc23, level1

#898 dark mode button hovers now
  src/Homepage/Homepage/DarkModeToggle.js
Labels: gssoc23, level1

#894 'Memory' Game Design Enhancement
  src/Games/Memory/memory.css
Labels: gssoc23, level1
