Repository ssitvit/Games-and-Go, pull requests merged in 2023-05, with the labels that each got.

#76 Trivia game card added
  src/Homepage/Data/data.js
Labels: GSSoC'23, easy

#90 added background music issue-30
  package-lock.json
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
  src/Homepage/Homepage/music1.mp3
Labels: GSSoC'23, easy

#103 Update README.md
  README.md
Labels: documentation, GSSoC'23, easy

#106 Revert "Re-Play Button added"
  src/Games/Ninetynine/ninetynine.css
  src/Games/Ninetynine/ninetynine.js
Labels: enhancement, GSSoC'23, easy

#117 15 puzzle game added
  package-lock.json
  src/Games/15Puzzle/App.js
  src/Games/15Puzzle/Fifteenpuzzle.css
  src/Games/15Puzzle/Fifteenpuzzle.js
  src/Games/15Puzzle/components/board/Board.css
  src/Games/15Puzzle/components/board/Board.js
  src/Games/15Puzzle/components/new-game/NewGame.css
  src/Games/15Puzzle/components/new-game/NewGame.js
  src/Games/15Puzzle/components/overlay/Overlay.css
  src/Games/15Puzzle/components/overlay/Overlay.js
  src/Games/15Puzzle/components/tile/Tile.css
  src/Games/15Puzzle/components/tile/Tile.js
  src/Games/15Puzzle/components/winner/Winner.css
  src/Games/15Puzzle/components/winner/Winner.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: GSSoC'23, easy

#127 [enhancement] update tic-tac-toe UI
  src/Games/Tictactoe/tictactoe.css
  src/Games/Tictactoe/tictactoe.js
Labels: enhancement, GSSoC'23, easy

#131 Games and go
  Contributors.md
  README.md
  src/Games/Simonsays/simon.css
  src/Games/Simonsays/simon.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: GSSoC'23, Level 2

#134 Added the Rock Paper and Scissors game to the Project
  Contributors.md
  src/Games/RockPaperScissors/RockPaperScissors.css
  src/Games/RockPaperScissors/RockPaperScissors.js
  src/Games/RockPaperScissors/assets/paper.png
  src/Games/RockPaperScissors/assets/rock.png
  src/Games/RockPaperScissors/assets/scissors.png
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: GSSoC'23, Level 2

#137 Brick breakout #86 PR2
  Contributors.md
  src/Games/BrickBreakout/BBdata.js
  src/Games/BrickBreakout/BallMovement.js
  src/Games/BrickBreakout/Board.js
  src/Games/BrickBreakout/Brick.js
  src/Games/BrickBreakout/BrickBreakout.css
  src/Games/BrickBreakout/BrickBreakout.js
  src/Games/BrickBreakout/Paddle.js
  src/Games/BrickBreakout/PlayerStats.js
  src/Games/BrickBreakout/util/AllBroke.js
  src/Games/BrickBreakout/util/BrickCollision.js
  src/Games/BrickBreakout/util/PaddleHit.js
  src/Games/BrickBreakout/util/ResetBall.js
  src/Games/BrickBreakout/util/WallCollision.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: GSSoC'23, Level 2

#150 Added Typo Game
  package-lock.json
  package.json
  src/Games/Typo/Typo.js
  src/Games/Typo/components/imported-text/ImportedText.js
  src/Games/Typo/components/imported-text/imported-text.css
  src/Games/Typo/components/main-game/MainGame.js
  src/Games/Typo/components/main-game/main-game.css
  src/Games/Typo/hooks/useTypo.js
  src/Games/Typo/typo.css
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: good first issue, GSSoC'23, Level 2

#156 added a new game
  package.json
  src/Games/BallShooting/BallShooting.jsx
  src/Games/BallShooting/CanvasComponent.jsx
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: GSSoC'23, Level 1

#176 Adding scroll to top button
  package-lock.json
  package.json
  src/Homepage/Homepage/GoToTop.js
  src/Homepage/Homepage/Homepage.js
Labels: good first issue, GSSoC'23, Level 1

#177 Depandabot added
  .github/dependabot.yaml
Labels: GSSoC'23, Level 1

#192 FREATURE added -new loader page issue-167
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: enhancement, GSSoC'23, Level 1

#262 Ball_Ninja Game
  src/Games/Ball_Ninja/README.md
  src/Games/Ball_Ninja/Sound_Source/Game-over.wav
  src/Games/Ball_Ninja/Sound_Source/Game-start.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-1.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-2.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-3.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-4.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-5.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-6.wav
  src/Games/Ball_Ninja/Sound_Source/Sword_Sound_Effects/Sword-swipe-7.wav
  src/Games/Ball_Ninja/Sound_Source/gank.wav
  src/Games/Ball_Ninja/Sound_Source/time-beep.wav
  src/Games/Ball_Ninja/Sound_Source/ui-button-push.wav
  src/Games/Ball_Ninja/index.html
  src/Games/Ball_Ninja/script.js
  src/Games/Ball_Ninja/srcImages/BNJG1.png
  src/Games/Ball_Ninja/srcImages/BNJG2.png
  src/Games/Ball_Ninja/srcImages/f4.png
  src/Games/Ball_Ninja/srcImages/github.png
  src/Games/Ball_Ninja/style.css
Labels: Level 3, GSSoC'23
