Repository ssitvit/Games-and-Go, pull requests merged in 2023-08, with the labels that each got.

#914 Improve the hover and the UI of the icon button
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/GoToTop.js
  src/Homepage/Homepage/MusicButton.js
Labels: gssoc23, level1

#913 Homepage Background Styling
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#904 music button hovering added
  src/Homepage/Homepage/MusicButton.js
Labels: gssoc23, level1

#921 feat: Dockerized the app
  .dockerignore
  Dockerfile
Labels: gssoc23, level2

#919 Added Flappy Bird and Retro Snake Game
  src/Games/Flappy Bird/TubeBody.png
  src/Games/Flappy Bird/TubeDown.png
  src/Games/Flappy Bird/TubeUp.png
  src/Games/Flappy Bird/background.jpg
  src/Games/Flappy Bird/bird.png
  src/Games/Flappy Bird/game.java
  src/Games/Flappy Bird/launch.json
  src/Games/Retro Snake Game/Main.java
  src/Games/Retro Snake Game/cherry.png
Labels: gssoc23, level2

#931 feat: made search bar accessible on homepage 🔍✨
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
Labels: gssoc23, level1

#929 added Next-Number-In-The-Sequence-Game
  src/Games/Next-Number-In-The-Sequence/README.md
  src/Games/Next-Number-In-The-Sequence/index.html
  src/Games/Next-Number-In-The-Sequence/script.js
  src/Games/Next-Number-In-The-Sequence/styles.css
Labels: gssoc23, level2

#925 Trivia Game Design Enhancement
  src/Games/Trivia/quiz.css
Labels: enhancement, gssoc23, level1

#924 Typo Typing Tester Game Design Enhancement
  src/Games/Typo/components/imported-text/imported-text.css
  src/Games/Typo/components/main-game/MainGame.js
  src/Games/Typo/components/main-game/main-game.css
  src/Games/Typo/typo.css
Labels: enhancement, gssoc23, level1

#937 color updated to green
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#933 Drag and Drop Game Design
  src/Games/DragAndDrop/App.css
  src/Games/DragAndDrop/components/card.css
  src/Games/DragAndDrop/index.css
Labels: gssoc23, level1

#959 Added dice showdown game
  package-lock.json
  src/Games/Dice-Throw/Dice.jsx
  src/Games/Dice-Throw/dice.css
  src/Games/Dice-Throw/images/dice1.png
  src/Games/Dice-Throw/images/dice2.png
  src/Games/Dice-Throw/images/dice3.png
  src/Games/Dice-Throw/images/dice4.png
  src/Games/Dice-Throw/images/dice5.png
  src/Games/Dice-Throw/images/dice6.png
  src/Homepage/Data/data.js
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/MusicButton.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: gssoc23, level2

#955 feat: add codeql workflow for code analysis 🔍✨
  .github/workflows/codeql.yml
Labels: gssoc23, level2

#953 Connect four game app.js and app.css
  src/Games/connect-four/app.css
  src/Games/connect-four/app.js
Labels: gssoc23, level2

#952 done
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#946 Footer Visibility and Text Readability
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level2

#820 feat: add sound effects for theme toggle button ✨
  src/Homepage/Homepage/DarkModeToggle.js
  src/Homepage/Homepage/audio_light-off.mp3
  src/Homepage/Homepage/audio_light-on.mp3
Labels: gssoc23, level2

#819 fix: incorrect padding of game container 🛠️
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level2

#799 fix: game card text overlapping during hover 🛠
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#766 dragon vs unicorn
  src/Games/tic-tac-toe 2/index.html
  src/Games/tic-tac-toe 2/script.js
  src/Games/tic-tac-toe 2/style.css
Labels: gssoc23, level2

#765 doraemon slide puzzle game
  src/Games/doraemon-slide-puzzle-game/1.jpg
  src/Games/doraemon-slide-puzzle-game/10.jpg
  src/Games/doraemon-slide-puzzle-game/2.jpg
  src/Games/doraemon-slide-puzzle-game/3.jpg
  src/Games/doraemon-slide-puzzle-game/4.jpg
  src/Games/doraemon-slide-puzzle-game/5.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/1.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/10.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/11.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/12.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/13.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/14.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/15.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/16.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/17.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/18.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/19.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/2.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/20.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/21.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/22.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/23.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/24.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/25.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/26.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/3.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/4.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/5.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/5_.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/6.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/7.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/8.jpg
  src/Games/doraemon-slide-puzzle-game/5x5 puzzle challenge/9.jpg
  src/Games/doraemon-slide-puzzle-game/6.jpg
  src/Games/doraemon-slide-puzzle-game/7.jpg
  src/Games/doraemon-slide-puzzle-game/8.jpg
  src/Games/doraemon-slide-puzzle-game/9.jpg
  src/Games/doraemon-slide-puzzle-game/index.html
  src/Games/doraemon-slide-puzzle-game/logo.png
  src/Games/doraemon-slide-puzzle-game/puzzle.css
  src/Games/doraemon-slide-puzzle-game/puzzle.js
Labels: gssoc23, level2

#764 rock paper scissor
  src/Games/Rock-Paper-Scissors/index.html
  src/Games/Rock-Paper-Scissors/paper.png
  src/Games/Rock-Paper-Scissors/rock.png
  src/Games/Rock-Paper-Scissors/scissors.png
  src/Games/Rock-Paper-Scissors/script.js
  src/Games/Rock-Paper-Scissors/style.css
Labels: gssoc23, level2

#734 Create lint.yml
  .github/workflows/lint.yml
Labels: gssoc23, level1

#635 Piano_Playing_Game Added
  src/Games/Piano_Playing_Game/.gitignore
  src/Games/Piano_Playing_Game/README.md
  src/Games/Piano_Playing_Game/img/piano_0.png
  src/Games/Piano_Playing_Game/img/piano_1.png
  src/Games/Piano_Playing_Game/img/piano_2.png
  src/Games/Piano_Playing_Game/package-lock.json
  src/Games/Piano_Playing_Game/package.json
  src/Games/Piano_Playing_Game/public/favicon.ico
  src/Games/Piano_Playing_Game/public/index.html
  src/Games/Piano_Playing_Game/public/logo192.png
  src/Games/Piano_Playing_Game/public/logo512.png
  src/Games/Piano_Playing_Game/public/manifest.json
  src/Games/Piano_Playing_Game/public/notes/a.mp3
  src/Games/Piano_Playing_Game/public/notes/af.mp3
  src/Games/Piano_Playing_Game/public/notes/b.mp3
  src/Games/Piano_Playing_Game/public/notes/bf.mp3
  src/Games/Piano_Playing_Game/public/notes/c.mp3
  src/Games/Piano_Playing_Game/public/notes/d.mp3
  src/Games/Piano_Playing_Game/public/notes/df.mp3
  src/Games/Piano_Playing_Game/public/notes/e.mp3
  src/Games/Piano_Playing_Game/public/notes/ef.mp3
  src/Games/Piano_Playing_Game/public/notes/f.mp3
  src/Games/Piano_Playing_Game/public/notes/g.mp3
  src/Games/Piano_Playing_Game/public/notes/gf.mp3
  src/Games/Piano_Playing_Game/public/robots.txt
  src/Games/Piano_Playing_Game/src/App.css
  src/Games/Piano_Playing_Game/src/App.js
  src/Games/Piano_Playing_Game/src/components/Key.css
  src/Games/Piano_Playing_Game/src/components/Key.js
  src/Games/Piano_Playing_Game/src/components/Piano.css
  src/Games/Piano_Playing_Game/src/components/Piano.js
  src/Games/Piano_Playing_Game/src/global/constants.js
  src/Games/Piano_Playing_Game/src/index.css
  src/Games/Piano_Playing_Game/src/index.js
  src/Games/Piano_Playing_Game/src/reportWebVitals.js
  src/Games/Piano_Playing_Game/src/setupTests.js
Labels: gssoc23, level2

#610 Create sitemap.xml
  public/sitemap.xml
Labels: gssoc23, level1

#969 Adding Word Scramble game.
  src/Games/wordScramble/.gitignore
  src/Games/wordScramble/README.md
  src/Games/wordScramble/package-lock.json
  src/Games/wordScramble/package.json
  src/Games/wordScramble/public/favicon.ico
  src/Games/wordScramble/public/index.html
  src/Games/wordScramble/public/logo192.png
  src/Games/wordScramble/public/logo512.png
  src/Games/wordScramble/public/manifest.json
  src/Games/wordScramble/public/robots.txt
  src/Games/wordScramble/src/App.css
  src/Games/wordScramble/src/App.js
  src/Games/wordScramble/src/App.test.js
  src/Games/wordScramble/src/FirstPage.css
  src/Games/wordScramble/src/FirstPage.js
  src/Games/wordScramble/src/Navbar.css
  src/Games/wordScramble/src/Navbar.js
  src/Games/wordScramble/src/SecondPage.css
  src/Games/wordScramble/src/SecondPage.js
  src/Games/wordScramble/src/index.css
  src/Games/wordScramble/src/index.js
  src/Games/wordScramble/src/reportWebVitals.js
  src/Games/wordScramble/src/setupTests.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level2

#968 Fixed rule color of TIC TAC TOE
  src/Games/Tictactoe/tictactoe.css
  src/Games/Tictactoe/tictactoe.js
Labels: gssoc23, level2

#965 Improve UI of search bar of Landing Page
  package-lock.json
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
  yarn.lock
Labels: gssoc23, level1

#966 Fixed alignment of darkmode button
  src/Homepage/Homepage/DarkModeToggle.js
Labels: gssoc23, level1

#992 [GSSoC'23] Fifteen Game ✔️
  src/Games/Fifteen_Game/Fifteen.js
  src/Games/Fifteen_Game/README.md
  src/Games/Fifteen_Game/art.jpg
  src/Games/Fifteen_Game/fifteenGame.css
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level2

#989 'Game On' Section Design Enhancement
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#985 'MineSweeper' Game Wrong Color Selection and Difficult Text Readability
  src/Games/Minesweeper/App.css
Labels: gssoc23, level1

#973 fix: play icon visibility on game cards ⚒️✨
  src/Homepage/Homepage/Play.js
Labels: gssoc23, level1

#974 fix: invisible "game on" heading during theme toggle ⚒️✨
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#975 Added hover and clicked effect on the A and B button
  src/Homepage/Homepage/Navbar.css
Labels: gssoc23, level1

#995 Added ContriButors list
  src/Homepage/Homepage/ContributorsList.js
  src/Homepage/Homepage/Homepage.js
  src/Homepage/Homepage/Teams.js
  src/Homepage/Homepage/contributors.css
Labels: gssoc23, level1

#1001 docs: improve readme
  README.md
Labels: gssoc23, level1

#998 [GSSoC'23] Guess Number Game Ready
  src/Games/Guess_The_Number/GuessNumber.css
  src/Games/Guess_The_Number/GuessNumber.js
  src/Games/Guess_The_Number/README.md
  src/Games/Guess_The_Number/sounds/correct.mp3
  src/Games/Guess_The_Number/sounds/end.mp3
  src/Games/Guess_The_Number/sounds/error.mp3
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: gssoc23, level2

#984 'Arkanoid' Game Errors
  src/Games/Arkanoid/App.css
Labels: gssoc23, level2

#980 fix: Update README.md
  README.md
Labels: documentation, gssoc23, level1

#1003 Added Validation for non-numeric input
  src/Games/guessing number/script.js
Labels: gssoc23, level1

#1032 Labyrinth of Death
  src/Games/Labyrinth of Death/minified/index.html
  src/Games/Labyrinth of Death/minified/minsrc.js
  src/Games/Labyrinth of Death/node_modules/.bin/roadroller
  src/Games/Labyrinth of Death/node_modules/.package-lock.json
  src/Games/Labyrinth of Death/node_modules/esm/LICENSE
  src/Games/Labyrinth of Death/node_modules/esm/README.md
  src/Games/Labyrinth of Death/node_modules/esm/esm.js
  src/Games/Labyrinth of Death/node_modules/esm/esm/loader.js
  src/Games/Labyrinth of Death/node_modules/esm/index.js
  src/Games/Labyrinth of Death/node_modules/esm/package.json
  src/Games/Labyrinth of Death/node_modules/roadroller/.github/workflows/gh-pages.yml
  src/Games/Labyrinth of Death/node_modules/roadroller/CHANGELOG.md
  src/Games/Labyrinth of Death/node_modules/roadroller/LICENSE.txt
  src/Games/Labyrinth of Death/node_modules/roadroller/README.md
  src/Games/Labyrinth of Death/node_modules/roadroller/cli.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/deflate.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/index.cjs
  src/Games/Labyrinth of Death/node_modules/roadroller/index.d.ts
  src/Games/Labyrinth of Death/node_modules/roadroller/index.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/js-tokens.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/package.json
  src/Games/Labyrinth of Death/node_modules/roadroller/test.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/tools/compare-size.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/tools/compress-demo.mjs
  src/Games/Labyrinth of Death/node_modules/roadroller/tools/demo-compressed.html
  src/Games/Labyrinth of Death/node_modules/roadroller/tools/demo-uncompressed.html
  src/Games/Labyrinth of Death/node_modules/roadroller/tools/demo.html
  src/Games/Labyrinth of Death/node_modules/roadroller/wasm.mjs
  src/Games/Labyrinth of Death/package-lock.json
  src/Games/Labyrinth of Death/package.json
  src/Games/Labyrinth of Death/polished build/index.html
  src/Games/Labyrinth of Death/polished build/src.js
Labels: gssoc23, level2

#1030 Pig_Game added
  src/Games/Pig_Game/README.md
  src/Games/Pig_Game/package-lock.json
  src/Games/Pig_Game/package.json
  src/Games/Pig_Game/public/favicon.ico
  src/Games/Pig_Game/public/index.html
  src/Games/Pig_Game/public/logo192.png
  src/Games/Pig_Game/public/logo512.png
  src/Games/Pig_Game/public/manifest.json
  src/Games/Pig_Game/public/robots.txt
  src/Games/Pig_Game/src/App.css
  src/Games/Pig_Game/src/App.js
  src/Games/Pig_Game/src/App.test.js
  src/Games/Pig_Game/src/Component/CommonPlayer.js
  src/Games/Pig_Game/src/Component/Dice.js
  src/Games/Pig_Game/src/Component/InputBox.js
  src/Games/Pig_Game/src/Component/ReactPigGame.js
  src/Games/Pig_Game/src/Component/Rules.js
  src/Games/Pig_Game/src/Component/SingleDice.js
  src/Games/Pig_Game/src/Component/style.css
  src/Games/Pig_Game/src/index.css
  src/Games/Pig_Game/src/index.js
  src/Games/Pig_Game/src/logo.svg
  src/Games/Pig_Game/src/serviceWorker.js
  src/Games/Pig_Game/src/setupTests.js
Labels: gssoc23, level2

#1029 enhanced README.md
  README.md
Labels: enhancement, gssoc23, level1

#1024 Added Cubula Game
  src/Games/Cubula/cubula0.gif
  src/Games/Cubula/cubula1.gif
  src/Games/Cubula/cubula2.gif
  src/Games/Cubula/cubula3.gif
  src/Games/Cubula/cubula4.gif
  src/Games/Cubula/index.html
  src/Games/Cubula/index.js
Labels: gssoc23, level2

#1021 'Game On' Section Boxes Design Enhancement
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level1

#1020 'ALPHABET GAME' Design Errors
  src/Games/Alphabet_Game/Alphabet.css
Labels: gssoc23, level1

#1012 feat: implement auto assign pr to author feature ✨
  .github/workflows/auto-assign-pr.yml
Labels: gssoc23, level2

#1011 remove: duplicate documentation issue template 🙅🏻❌
  .github/ISSUE_TEMPLATE/doc.yml
Labels: gssoc23, level1

#1010 feat: implement issue lockdown feature to reduce unwanted notifications 🔐✨
  .github/ISSUE_TEMPLATE/lock-newly-opened-issues.yml
Labels: gssoc23, level2

#1004 feat: Added dynamic contributors section
  README.md
Labels: gssoc23, level2

#1053 doodle game jump
  src/Games/doodle-jump/doodlejump.css
  src/Games/doodle-jump/doodlejump.js
  src/Games/doodle-jump/doodlejumpbg.png
  src/Games/doodle-jump/doodler-left.png
  src/Games/doodle-jump/doodler-right.png
  src/Games/doodle-jump/index.html
  src/Games/doodle-jump/platform-broken.png
  src/Games/doodle-jump/platform.png
Labels: gssoc23, level2

#1052 fixes -bird shooter game
  src/Games/bird-shooter-game/Readme.md
  src/Games/bird-shooter-game/index.html
  src/Games/bird-shooter-game/style.css
Labels: gssoc23, level2

#1051 fixes #889
  src/Games/maze game/index.html
  src/Games/maze game/script.js
  src/Games/maze game/style.css
Labels: gssoc23, level2

#1036 Added Quiz Game App
  src/Games/Quiz Game App/.gitignore
  src/Games/Quiz Game App/README.md
  src/Games/Quiz Game App/package-lock.json
  src/Games/Quiz Game App/package.json
  src/Games/Quiz Game App/public/favicon.ico
  src/Games/Quiz Game App/public/index.html
  src/Games/Quiz Game App/public/logo192.png
  src/Games/Quiz Game App/public/logo512.png
  src/Games/Quiz Game App/public/manifest.json
  src/Games/Quiz Game App/public/quiz.json
  src/Games/Quiz Game App/public/robots.txt
  src/Games/Quiz Game App/src/App.css
  src/Games/Quiz Game App/src/App.js
  src/Games/Quiz Game App/src/App.test.js
  src/Games/Quiz Game App/src/components/Quiz.js
  src/Games/Quiz Game App/src/components/Result.js
  src/Games/Quiz Game App/src/components/Start.js
  src/Games/Quiz Game App/src/index.css
  src/Games/Quiz Game App/src/index.js
  src/Games/Quiz Game App/src/logo.svg
  src/Games/Quiz Game App/src/reportWebVitals.js
  src/Games/Quiz Game App/src/setupTests.js
Labels: gssoc23, level2

#1048 Added Start Reactor game #1016
  src/Games/Start_reactor_Game/README.md
  src/Games/Start_reactor_Game/demo.png
  src/Games/Start_reactor_Game/files/audio/completed.mp3
  src/Games/Start_reactor_Game/files/audio/tapsound.ogg
  src/Games/Start_reactor_Game/files/audio/win.mp3
  src/Games/Start_reactor_Game/files/audio/wrong.ogg
  src/Games/Start_reactor_Game/files/images/amongusbg.gif
  src/Games/Start_reactor_Game/files/images/checked.png
  src/Games/Start_reactor_Game/files/images/index.png
  src/Games/Start_reactor_Game/files/images/loose.gif
  src/Games/Start_reactor_Game/files/images/tick.png
  src/Games/Start_reactor_Game/files/images/win.gif
  src/Games/Start_reactor_Game/index.html
  src/Games/Start_reactor_Game/script.js
  src/Games/Start_reactor_Game/styles.css
Labels: gssoc23, level2

#1046 Chess_Game added
  src/Games/Chess_Game/BKnight.png
  src/Games/Chess_Game/Bbishop.png
  src/Games/Chess_Game/Bking.png
  src/Games/Chess_Game/Bpawn.png
  src/Games/Chess_Game/Bqueen.png
  src/Games/Chess_Game/Brook.png
  src/Games/Chess_Game/Chess.css
  src/Games/Chess_Game/Chess.js
  src/Games/Chess_Game/README.md
  src/Games/Chess_Game/WKnight.png
  src/Games/Chess_Game/Wbishop.png
  src/Games/Chess_Game/Wking.png
  src/Games/Chess_Game/Wpawn.png
  src/Games/Chess_Game/Wqueen.png
  src/Games/Chess_Game/Wrook.png
  src/Games/Chess_Game/index.html
Labels: gssoc23, level2

#1042 [Bug]: 'GuessTheColor' Game Errors
  src/Games/GuessTheColor/src/guess.css
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level2

#1041 [FEATURE] - Game On Section Content Design Enhancement
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level2

#1040 docs: improve readability by replacing small images into attractive badges 📛✨
  README.md
Labels: gssoc23, level2

#1039 feat: made gssoc banner responsive to github light/dark mode 🌞/🌚 💡✨
  README.md
Labels: gssoc23, level2

#1037 Added LetterFusion Puzzler Game
  src/Games/LetterFusion Puzzler Game/.gitignore
  src/Games/LetterFusion Puzzler Game/README.md
  src/Games/LetterFusion Puzzler Game/package-lock.json
  src/Games/LetterFusion Puzzler Game/package.json
  src/Games/LetterFusion Puzzler Game/public/index.html
  src/Games/LetterFusion Puzzler Game/public/manifest.json
  src/Games/LetterFusion Puzzler Game/public/robots.txt
  src/Games/LetterFusion Puzzler Game/src/App.js
  src/Games/LetterFusion Puzzler Game/src/components/FormingWordLettersRecipient.js
  src/Games/LetterFusion Puzzler Game/src/components/GameApp.js
  src/Games/LetterFusion Puzzler Game/src/components/GuessedWordsRecipient.js
  src/Games/LetterFusion Puzzler Game/src/components/MatchLetterButton.js
  src/Games/LetterFusion Puzzler Game/src/components/MatchLettersRecipient.js
  src/Games/LetterFusion Puzzler Game/src/components/StatsChart.js
  src/Games/LetterFusion Puzzler Game/src/components/SubmitButton.js
  src/Games/LetterFusion Puzzler Game/src/context/GameContext.js
  src/Games/LetterFusion Puzzler Game/src/index.css
  src/Games/LetterFusion Puzzler Game/src/index.js
  src/Games/LetterFusion Puzzler Game/src/reportWebVitals.js
  src/Games/LetterFusion Puzzler Game/src/setupTests.js
  src/Games/LetterFusion Puzzler Game/src/utils/letters.js
  src/Games/LetterFusion Puzzler Game/src/utils/words.js
  src/Games/LetterFusion Puzzler Game/tailwind.config.js
Labels: gssoc23, level2

#1055 highway car race game
  src/Games/highway-race/dist/index.html
  src/Games/highway-race/dist/script.js
  src/Games/highway-race/dist/style.css
  src/Games/highway-race/src/index.html
  src/Games/highway-race/src/script.js
  src/Games/highway-race/src/style.css
Labels: gssoc23, level2

#1062 [Feature Request]: Contributor Section Design
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/contributors.css
Labels: gssoc23, level2

#1057 Code quality Improvements
  src/ErrorPage/ErrorPage.js
Labels: gssoc23, level2

#1061 Added Pokemon App
  src/Games/Pokemon/.gitignore
  src/Games/Pokemon/README.md
  src/Games/Pokemon/package-lock.json
  src/Games/Pokemon/package.json
  src/Games/Pokemon/public/favicon.ico
  src/Games/Pokemon/public/index.html
  src/Games/Pokemon/public/logo192.png
  src/Games/Pokemon/public/logo512.png
  src/Games/Pokemon/public/manifest.json
  src/Games/Pokemon/public/pokeball.ico
  src/Games/Pokemon/public/robots.txt
  src/Games/Pokemon/src/App.js
  src/Games/Pokemon/src/App.test.js
  src/Games/Pokemon/src/Components/Description.js
  src/Games/Pokemon/src/Components/PokemonThumbnail.js
  src/Games/Pokemon/src/index.css
  src/Games/Pokemon/src/index.js
Labels: gssoc23, level2

#1058 [Bug]: 'Battle Ships' Game Errors
  src/Games/BattleShip/App.css
Labels: gssoc23, level2

#1063 remove development game
  src/Games/Planet_Defense/README.md
  src/Games/Planet_Defense/index.html
  src/Games/Planet_Defense/script.js
  src/Games/Planet_Defense/space.webp
  src/Games/Planet_Defense/style.css
  src/Games/Pong_Game/game.html
  src/Games/Pong_Game/index.html
  src/Games/Pong_Game/script.js
  src/Games/Pong_Game/style.css
  src/Games/Pong_Game/winner.html
  src/Games/SIMON GAME/game.js
  src/Games/SIMON GAME/index.html
  src/Games/SIMON GAME/sounds/blue.mp3
  src/Games/SIMON GAME/sounds/green.mp3
  src/Games/SIMON GAME/sounds/red.mp3
  src/Games/SIMON GAME/sounds/wrong.mp3
  src/Games/SIMON GAME/sounds/yellow.mp3
  src/Games/SIMON GAME/styles.css
  src/Games/Tower_Blocks/README.md
  src/Games/Tower_Blocks/index.html
  src/Games/Tower_Blocks/script.js
  src/Games/Tower_Blocks/style.css
  src/Games/snake-game/index.html
  src/Games/snake-game/snake.css
  src/Games/snake-game/snake.js
  src/Homepage/Data/data.js
Labels: gssoc23, level2

#1078 Added Eight Queens Game
  src/Games/Eight Queens Game/.gitignore
  src/Games/Eight Queens Game/README.md
  src/Games/Eight Queens Game/package.json
  src/Games/Eight Queens Game/public/favicon.ico
  src/Games/Eight Queens Game/public/index.html
  src/Games/Eight Queens Game/public/manifest.json
  src/Games/Eight Queens Game/src/DidYouKnow.js
  src/Games/Eight Queens Game/src/EightQueens.css
  src/Games/Eight Queens Game/src/EightQueens.js
  src/Games/Eight Queens Game/src/EightQueens.test.js
  src/Games/Eight Queens Game/src/Status.css
  src/Games/Eight Queens Game/src/Status.js
  src/Games/Eight Queens Game/src/Tidbits.js
  src/Games/Eight Queens Game/src/Timer.css
  src/Games/Eight Queens Game/src/Timer.js
  src/Games/Eight Queens Game/src/Title.css
  src/Games/Eight Queens Game/src/Title.js
  src/Games/Eight Queens Game/src/UnderAttack.js
  src/Games/Eight Queens Game/src/helpers.js
  src/Games/Eight Queens Game/src/index.css
  src/Games/Eight Queens Game/src/index.js
  src/Games/Eight Queens Game/src/queenUnderAttack.svg
  src/Games/Eight Queens Game/src/serviceWorker.js
  src/Games/Eight Queens Game/yarn.lock
Labels: gssoc23, level2

#1077 background colour corrected
  src/Homepage/Homepage/GoToTop.js
Labels: gssoc23, level2

#1075 Added Ludo Game
  src/Games/Ludo Game/.gitignore
  src/Games/Ludo Game/README.md
  src/Games/Ludo Game/package-lock.json
  src/Games/Ludo Game/package.json
  src/Games/Ludo Game/public/favicon.ico
  src/Games/Ludo Game/public/index.html
  src/Games/Ludo Game/public/logo192.png
  src/Games/Ludo Game/public/logo512.png
  src/Games/Ludo Game/public/manifest.json
  src/Games/Ludo Game/public/robots.txt
  src/Games/Ludo Game/src/App.css
  src/Games/Ludo Game/src/App.js
  src/Games/Ludo Game/src/App.test.js
  src/Games/Ludo Game/src/Capture.PNG
  src/Games/Ludo Game/src/components/Box.js
  src/Games/Ludo Game/src/components/Button.js
  src/Games/Ludo Game/src/components/FrontEnd.js
  src/Games/Ludo Game/src/components/circle.js
  src/Games/Ludo Game/src/img-left.css
  src/Games/Ludo Game/src/img-left.js
  src/Games/Ludo Game/src/index.css
  src/Games/Ludo Game/src/index.js
  src/Games/Ludo Game/src/logo.svg
  src/Games/Ludo Game/src/serviceWorker.js
  src/Games/Ludo Game/src/setupTests.js
  src/Games/Ludo Game/yarn.lock
Labels: gssoc23, level2

#1070 [Feature Request]: Search Area Design Enhancement #1067
  src/Homepage/Homepage/Homepage.css
Labels: gssoc23, level2

#1069 added flappy bubble sofa game
  src/Games/Flappy_Bubble_sofa/README.md
  src/Games/Flappy_Bubble_sofa/assets/css/styles.css
  src/Games/Flappy_Bubble_sofa/assets/img/logo.png
  src/Games/Flappy_Bubble_sofa/assets/js/main.js
  src/Games/Flappy_Bubble_sofa/assets/readme/image-1.png
  src/Games/Flappy_Bubble_sofa/assets/readme/image.png
  src/Games/Flappy_Bubble_sofa/index.html
Labels: gssoc23, level2

#1068 Added Brick Blaster game #1054
  src/Games/Brick_Blaster/assets/css/style.css
  src/Games/Brick_Blaster/assets/images/.gitignore
  src/Games/Brick_Blaster/assets/images/blaster.png
  src/Games/Brick_Blaster/assets/images/bomb.png
  src/Games/Brick_Blaster/assets/images/bomb1.png
  src/Games/Brick_Blaster/assets/images/border1.png
  src/Games/Brick_Blaster/assets/images/border2.png
  src/Games/Brick_Blaster/assets/images/chest.png
  src/Games/Brick_Blaster/image.png
  src/Games/Brick_Blaster/index.html
  src/Games/Brick_Blaster/readme.md
  src/Games/Brick_Blaster/src/brickblaster/.gitignore
  src/Games/Brick_Blaster/src/brickblaster/engine.js
  src/Games/Brick_Blaster/src/brickblaster/game.js
Labels: gssoc23, level2

#1082 Added Candy Crush Game
  src/Games/Candy Crush Game/.gitignore
  src/Games/Candy Crush Game/README.md
  src/Games/Candy Crush Game/package-lock.json
  src/Games/Candy Crush Game/package.json
  src/Games/Candy Crush Game/postcss.config.js
  src/Games/Candy Crush Game/public/favicon.ico
  src/Games/Candy Crush Game/public/index.html
  src/Games/Candy Crush Game/public/logo192.png
  src/Games/Candy Crush Game/public/logo512.png
  src/Games/Candy Crush Game/public/manifest.json
  src/Games/Candy Crush Game/public/robots.txt
  src/Games/Candy Crush Game/src/App.tsx
  src/Games/Candy Crush Game/src/assets/background.png
  src/Games/Candy Crush Game/src/assets/candyFive.png
  src/Games/Candy Crush Game/src/assets/candyFour.png
  src/Games/Candy Crush Game/src/assets/candyOne.png
  src/Games/Candy Crush Game/src/assets/candySeven.png
  src/Games/Candy Crush Game/src/assets/candySix.png
  src/Games/Candy Crush Game/src/assets/candyThree.png
  src/Games/Candy Crush Game/src/assets/candyTwo.png
  src/Games/Candy Crush Game/src/components/Board.tsx
  src/Games/Candy Crush Game/src/components/Tile.tsx
  src/Games/Candy Crush Game/src/index.css
  src/Games/Candy Crush Game/src/index.tsx
  src/Games/Candy Crush Game/src/react-app-env.d.ts
  src/Games/Candy Crush Game/src/store/hooks.ts
  src/Games/Candy Crush Game/src/store/index.ts
  src/Games/Candy Crush Game/src/store/reducers/dragEnd.ts
  src/Games/Candy Crush Game/src/store/reducers/moveBelow.ts
  src/Games/Candy Crush Game/src/utils/candyData.ts
  src/Games/Candy Crush Game/src/utils/createBoard.ts
  src/Games/Candy Crush Game/src/utils/formulas.ts
  src/Games/Candy Crush Game/src/utils/moveCheckLogic.ts
  src/Games/Candy Crush Game/tailwind.config.js
  src/Games/Candy Crush Game/tsconfig.json
  src/Games/Candy Crush Game/yarn.lock
Labels: gssoc23, level2
