Repository ssitvit/Games-and-Go, pull requests merged in 2023-06, with the labels that each got.

#194 added hover effect to play button
  package-lock.json
  package.json
  src/Homepage/Homepage/Homepage.css
Labels: GSSoC'23, Level 1

#196 close old issues action added
  .github/dependabot.yaml
  .github/workflows/close_old_issues.yaml
Labels: bug, GSSoC'23, Level 1

#237 Modified some UI in Tic-Tac-Toe for making it clear and clean to use. 🍉
  src/Games/Tictactoe/tictactoe.css
  src/Games/Tictactoe/tictactoe.js
Labels: GSSoC'23, Level 1

#238 Adding 2048game
  src/Games/2048game/2048.css
  src/Games/2048game/2048.js
  src/Games/2048game/index.html
Labels: enhancement, GSSoC'23, Level 2

#239 Modified the UI of ninety-nine game (i.e., Added a button to display the status of winning).🍉
  src/Games/Ninetynine/ninetynine.css
  src/Games/Ninetynine/ninetynine.js
Labels: GSSoC'23, Level 2

#247 Added a button type format to display the score in Rock-Paper-Scissors Game 🍉
  src/Games/RockPaperScissors/RockPaperScissors.css
  src/Games/RockPaperScissors/RockPaperScissors.js
Labels: enhancement, GSSoC'23, Level 1

#332 fixed the pacman animation
  src/App.js
  src/Homepage/Homepage/Homepage.css
Labels: bug, enhancement, good first issue, Level 3, GSSoC'23

#334 New scrollbar for website
  src/Homepage/Homepage/Homepage.css
Labels: enhancement, GSSoC'23, Level 2

#336 fixes in preloader
  src/App.css
  src/App.js
Labels: enhancement, GSSoC'23, Level 2

#349 added copyrights to the footer
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
Labels: enhancement, Level 3, GSSoC'23

#355 Revert "catch_the_bottle_added"
  src/Games/catch_the_bottle/bottle.png
  src/Games/catch_the_bottle/box1.png
  src/Games/catch_the_bottle/broken1.png
  src/Games/catch_the_bottle/collision_detection.js
  src/Games/catch_the_bottle/functions.js
  src/Games/catch_the_bottle/index.html
  src/Games/catch_the_bottle/jquery.min.js
  src/Games/catch_the_bottle/script.js
  src/Games/catch_the_bottle/style.css
  src/Games/catch_the_bottle/variables.js
Labels: bug, GSSoC'23, Level 1

#357 Snake Game #2
  src/Games/SnakeGame/SnakeGame.css
  src/Games/SnakeGame/SnakeGame.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, GSSoC'23, Level 2

#361 Revert "[ New Game ] : Added Dice_Showdown_Game { GSSOC'23 }"
  src/Games/Dice_Showdown_Game/dicee.html
  src/Games/Dice_Showdown_Game/images/dice1.png
  src/Games/Dice_Showdown_Game/images/dice2.png
  src/Games/Dice_Showdown_Game/images/dice3.png
  src/Games/Dice_Showdown_Game/images/dice4.png
  src/Games/Dice_Showdown_Game/images/dice5.png
  src/Games/Dice_Showdown_Game/images/dice6.png
  src/Games/Dice_Showdown_Game/index.js
  src/Games/Dice_Showdown_Game/styles.css
Labels: bug, enhancement, GSSoC'23, Level 2

#362 Revert "Added Drumkit game- GSSoC"
  src/Games/DrumKit/DrumKit.css
  src/Games/DrumKit/DrumKit.html
  src/Games/DrumKit/DrumKit.js
  src/Games/DrumKit/images/crash.png
  src/Games/DrumKit/images/kick.png
  src/Games/DrumKit/images/snare.png
  src/Games/DrumKit/images/tom1.png
  src/Games/DrumKit/images/tom2.png
  src/Games/DrumKit/images/tom3.png
  src/Games/DrumKit/images/tom4.png
  src/Games/DrumKit/sounds/crash.mp3
  src/Games/DrumKit/sounds/kick-bass.mp3
  src/Games/DrumKit/sounds/snare.mp3
  src/Games/DrumKit/sounds/tom-1.mp3
  src/Games/DrumKit/sounds/tom-2.mp3
  src/Games/DrumKit/sounds/tom-3.mp3
  src/Games/DrumKit/sounds/tom-4.mp3
Labels: bug, enhancement, GSSoC'23, Level 2

#363 Improve Navbar and Scroll Effect
  src/App.css
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Navbar.css
Labels: enhancement, GSSoC'23, Level 1

#365 Added TOC to readme and restyled
  Contributors.md
  README.md
Labels: documentation, good first issue, GSSoC'23, Level 1

#366 Fixed #339 - Implemented Music Toggle Button
  src/Homepage/Homepage/Homepage.js
  src/Homepage/Homepage/MusicButton.js
Labels: enhancement, good first issue, GSSoC'23, Level 2

#368 Improve Animation for mobile devices
  src/App.js
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
Labels: enhancement, GSSoC'23, Level 2

#373 Removed flappy bird game
  package-lock.json
  src/Games/Flappy-Bird-Game/README.md
  src/Games/Flappy-Bird-Game/images/Bird-2.png
  src/Games/Flappy-Bird-Game/images/Bird.png
  src/Games/Flappy-Bird-Game/images/background-img.png
  src/Games/Flappy-Bird-Game/images/favicon.ico
  src/Games/Flappy-Bird-Game/index.html
  src/Games/Flappy-Bird-Game/script.js
  src/Games/Flappy-Bird-Game/sounds effect/die.mp3
  src/Games/Flappy-Bird-Game/sounds effect/point.mp3
  src/Games/Flappy-Bird-Game/style.css
Labels: GSSoC'23, Level 1

#387 Added tetris game to the routes
  src/Games/tetris/src/components/styles/StyledTetris.js
  src/Games/tetris/src/img/bg.jpg
  src/Games/tetris/src/img/bg.png
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: GSSoC'23, Level 1

#388 issue #139 added Battle Ship Game
  package-lock.json
  package.json
  src/Games/BattleShip/App.css
  src/Games/BattleShip/App.js
  src/Games/BattleShip/App.test.js
  src/Games/BattleShip/Board.js
  src/Games/BattleShip/ShipsRemaining.js
  src/Games/BattleShip/Square.js
  src/Games/BattleShip/index.css
  src/Games/BattleShip/index.js
  src/Games/BattleShip/registerServiceWorker.js
  src/Games/BattleShip/style2.css
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, good first issue, GSSoC'23, Level 2

#393 Revert "Boxing Game by Shubham For GSSoC'23"
  src/Games/Boxing_Game/index.html
  src/Games/Boxing_Game/script.js
  src/Games/Boxing_Game/style.css
Labels: bug, GSSoC'23, Level 1

#401 drag-and-drop game added #391
  src/Games/DragAndDrop/App.css
  src/Games/DragAndDrop/App.js
  src/Games/DragAndDrop/components/blue.js
  src/Games/DragAndDrop/components/card.css
  src/Games/DragAndDrop/components/green.js
  src/Games/DragAndDrop/components/orange.js
  src/Games/DragAndDrop/components/purple.js
  src/Games/DragAndDrop/components/red.js
  src/Games/DragAndDrop/components/yellow.js
  src/Games/DragAndDrop/index.css
  src/Games/DragAndDrop/index.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, good first issue, GSSoC'23, Level 2

#397 Make Animation Responsive
  src/Homepage/Homepage/Homepage.css
Labels: bug, enhancement, Level 3, GSSoC'23

#407 Revert "add to readme"
  Contributors.md
  README.md
Labels: bug, enhancement, GSSoC'23, Level 1

#409 Improve Style
  src/Homepage/Homepage/Homepage.css
Labels: GSSoC'23, Level 1

#410 Adding hover to music button and go to top button
  src/Homepage/Homepage/GoToTop.js
  src/Homepage/Homepage/MusicButton.js
Labels: enhancement, good first issue, GSSoC'23, Level 1

#411 Improve loading animation
  src/App.css
  src/App.js
Labels: enhancement, GSSoC'23, Level 2

#413 Start again card in ball Shooting game #325 Fixed
  src/Games/BallShooting/BallShooting.css
Labels: bug, good first issue, GSSoC'23, Level 2

#415 Added meta tags
  public/index.html
Labels: enhancement, GSSoC'23, Level 1

#418 Update README.md
  README.md
Labels: good first issue, GSSoC'23, Level 1

#419 Update README.md
  README.md
Labels: bug, GSSoC'23, Level 1

#420 Resolved merge conflicts and added AI mode in TicTacToe
  package-lock.json
  package.json
  src/Games/TicTactoeAI/app.js
  src/Games/TicTactoeAI/components/Button.jsx
  src/Games/TicTactoeAI/components/Square.jsx
  src/Games/TicTactoeAI/components/Square.scss
  src/Games/TicTactoeAI/images/pic.jpg
  src/Games/TicTactoeAI/index.css
  src/Games/TicTactoeAI/index.js
  src/Games/Tictactoe/tictactoe.css
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, good first issue, Level 3, GSSoC'23

#421 Update Homepage.css
  src/Homepage/Homepage/Homepage.css
Labels: bug, enhancement, GSSoC'23, Level 2

#424 Fix MusicButton auto-play issue on homepage
  src/Homepage/Homepage/MusicButton.js
Labels: bug, good first issue, GSSoC'23, Level 1

#430 changed class to className
  src/Games/BallShooting/BallShooting.jsx
  src/Homepage/Homepage/Navbar.js
Labels: bug, good first issue, GSSoC'23, Level 1

#462 Revert "Gitsszbrnch"
  src/Games/DiceThrow/main.js
  src/Games/DiceThrow/styles.css
  src/Games/Typo/components/imported-text/imported-text.css
  src/Games/Typo/components/main-game/MainGame.js
  src/Games/Typo/components/main-game/main-game.css
  src/Games/Typo/typo.css
Labels: bug, GSSoC'23, Level 1

#465 New Game Arkanoid
  src/Games/Arkanoid/App.css
  src/Games/Arkanoid/App.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, GSSoC'23, Level 2

#481 Added Simon Game
  src/Games/SIMON GAME/game.js
  src/Games/SIMON GAME/index.html
  src/Games/SIMON GAME/sounds/blue.mp3
  src/Games/SIMON GAME/sounds/green.mp3
  src/Games/SIMON GAME/sounds/red.mp3
  src/Games/SIMON GAME/sounds/wrong.mp3
  src/Games/SIMON GAME/sounds/yellow.mp3
  src/Games/SIMON GAME/styles.css
Labels: GSSoC'23, Level 1

#493 [Feature Request]: Drag & Drop - size of table fixed
  src/Games/DragAndDrop/App.css
Labels: GSSoC'23, Level 1

#492 Fixed issue #452
  public/_redirects
Labels: GSSoC'23, Level 1

#491 Start Button Commit
  src/Games/Memory/memory.js
Labels: bug, GSSoC'23, Level 2

#494 Revert "Fixed issue #452"
  public/_redirects
Labels: bug, GSSoC'23, Level 1

#495 Added Dice Challenge Game
  src/Games/Dice Game/dicee.html
  src/Games/Dice Game/images/dice1.png
  src/Games/Dice Game/images/dice2.png
  src/Games/Dice Game/images/dice3.png
  src/Games/Dice Game/images/dice4.png
  src/Games/Dice Game/images/dice5.png
  src/Games/Dice Game/images/dice6.png
  src/Games/Dice Game/index.js
  src/Games/Dice Game/styles.css
Labels: GSSoC'23, Level 2

#496 Added Hover Effect in SnakeGame
  package-lock.json
  package.json
  src/Games/SnakeGame/SnakeGame.css
Labels: hacktoberfest, GSSoC'23, Level 1

#499 Revert "Added Dice Challenge Game"
  src/Games/Dice Game/dicee.html
  src/Games/Dice Game/images/dice1.png
  src/Games/Dice Game/images/dice2.png
  src/Games/Dice Game/images/dice3.png
  src/Games/Dice Game/images/dice4.png
  src/Games/Dice Game/images/dice5.png
  src/Games/Dice Game/images/dice6.png
  src/Games/Dice Game/index.js
  src/Games/Dice Game/styles.css
Labels: bug, GSSoC'23, Level 1

#502 Fixed issue #452: Page Not Found
  public/_redirects
Labels: bug, good first issue, GSSoC'23, Level 2

#507 Update snake game UI and add score feature
  src/Games/SnakeGame/SnakeGame.css
  src/Games/SnakeGame/SnakeGame.js
  src/Games/SnakeGame/bg.jpg
Labels: enhancement, GSSoC'23, Level 2

#511 Updated the homepage
  src/updateContributor.js
Labels: enhancement, GSSoC'23, Level 1

#512 Updated Contributing.md
  Contributing.md
Labels: documentation, GSSoC'23, Level 1

#513 Update SnakeGame.css
  src/Games/SnakeGame/SnakeGame.css
Labels: GSSoC'23, Level 1

#516 Alignment of trivia game page
  src/Games/Trivia/quiz.css
  src/Games/Trivia/quiz.js
Labels: enhancement, GSSoC'23, Level 1

#514 Added about section in homepage
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
Labels: enhancement, GSSoC'23, Level 2

#523 Magic Matching UI has been improved
  src/Games/Magic-match/components/SingleCard.css
  src/Games/Magic-match/magic_match.css
  src/Games/Magic-match/magic_match.js
Labels: enhancement, GSSoC'23, Level 2

#525 Created Chess AI with react
  babel.config.js
  package-lock.json
  package.json
  src/Games/ChessAI/.eslintcache
  src/Games/ChessAI/.gitignore
  src/Games/ChessAI/README.md
  src/Games/ChessAI/appiz.js
  src/Games/ChessAI/package.json
  src/Games/ChessAI/public/favicon.ico
  src/Games/ChessAI/public/index.html
  src/Games/ChessAI/public/logo192.png
  src/Games/ChessAI/public/logo512.png
  src/Games/ChessAI/public/manifest.json
  src/Games/ChessAI/public/robots.txt
  src/Games/ChessAI/src/App.css
  src/Games/ChessAI/src/App.test.tsx
  src/Games/ChessAI/src/index.css
  src/Games/ChessAI/src/index.tsx
  src/Games/ChessAI/src/logo.svg
  src/Games/ChessAI/src/react-app-env.d.ts
  src/Games/ChessAI/src/reportWebVitals.ts
  src/Games/ChessAI/src/setupTests.ts
  src/Games/ChessAI/tsconfig.json
  src/Games/ChessAI/yarn.lock
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: enhancement, Level 3, GSSoC'23

#528 Created Tenzies Game
  src/Games/Tenzies/App.js
  src/Games/Tenzies/Die.js
  src/Games/Tenzies/README.md
  src/Games/Tenzies/index.html
  src/Games/Tenzies/index.js
  src/Games/Tenzies/package.json
  src/Games/Tenzies/style.css
  src/Games/Tenzies/webpack.config.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, GSSoC'23, Level 2

#489 Minesweeper game added
  Contributors.md
  package-lock.json
  package.json
  src/Games/Minesweeper/App.css
  src/Games/Minesweeper/App.js
  src/Games/Minesweeper/Components/Board.js
  src/Games/Minesweeper/Components/Cell.js
  src/Games/Minesweeper/Utils/CreateBoard.js
  src/Games/Minesweeper/Utils/Reveal.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, good first issue, Level 3, GSSoC'23

#542 Revert "Created Tenzies Game"
  src/Games/Tenzies/App.js
  src/Games/Tenzies/Die.js
  src/Games/Tenzies/README.md
  src/Games/Tenzies/index.html
  src/Games/Tenzies/index.js
  src/Games/Tenzies/package.json
  src/Games/Tenzies/style.css
  src/Games/Tenzies/webpack.config.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: bug, GSSoC'23, Level 1

#543 Revert "Minesweeper game added"
  Contributors.md
  package-lock.json
  package.json
  src/Games/Minesweeper/App.css
  src/Games/Minesweeper/App.js
  src/Games/Minesweeper/Components/Board.js
  src/Games/Minesweeper/Components/Cell.js
  src/Games/Minesweeper/Utils/CreateBoard.js
  src/Games/Minesweeper/Utils/Reveal.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: bug, GSSoC'23, Level 1

#544 Revert "Revert "Minesweeper game added""
  Contributors.md
  package-lock.json
  package.json
  src/Games/Minesweeper/App.css
  src/Games/Minesweeper/App.js
  src/Games/Minesweeper/Components/Board.js
  src/Games/Minesweeper/Components/Cell.js
  src/Games/Minesweeper/Utils/CreateBoard.js
  src/Games/Minesweeper/Utils/Reveal.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: bug, GSSoC'23, Level 1

#546 Update data.js
  src/Homepage/Data/data.js
Labels: enhancement, GSSoC'23, Level 1

#547 Jump and Run game added
  src/Games/Jump and run/ReadMe.md
  src/Games/Jump and run/index.html
  src/Games/Jump and run/script.js
  src/Games/Jump and run/style.css
Labels: hacktoberfest, gssoc23, level1

#562 Revert "Jump and Run game added"
  src/Games/Jump and run/ReadMe.md
  src/Games/Jump and run/index.html
  src/Games/Jump and run/script.js
  src/Games/Jump and run/style.css
Labels: enhancement, gssoc23, level2

#548 Drum-Kit
  package-lock.json
  src/Games/Drum-Kit/DrumKit.css
  src/Games/Drum-Kit/DrumKit.js
  src/Games/Drum-Kit/Images/crash.png
  src/Games/Drum-Kit/Images/kick.png
  src/Games/Drum-Kit/Images/snare.png
  src/Games/Drum-Kit/Images/tom1.png
  src/Games/Drum-Kit/Images/tom2.png
  src/Games/Drum-Kit/Images/tom3.png
  src/Games/Drum-Kit/Images/tom4.png
  src/Games/Drum-Kit/Sounds/crash.mp3
  src/Games/Drum-Kit/Sounds/kick-bass.mp3
  src/Games/Drum-Kit/Sounds/snare.mp3
  src/Games/Drum-Kit/Sounds/tom-1.mp3
  src/Games/Drum-Kit/Sounds/tom-2.mp3
  src/Games/Drum-Kit/Sounds/tom-3.mp3
  src/Games/Drum-Kit/Sounds/tom-4.mp3
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, gssoc23, level2

#563 Update README.md
  README.md
Labels: enhancement, gssoc23, level2

#584 Adding a flip feature to card to show rules of game
  Contributors.md
  package-lock.json
  src/Homepage/Data/data.js
  src/Homepage/Homepage/Homepage.css
  src/Homepage/Homepage/Homepage.js
  yarn.lock
Labels: enhancement, good first issue, level3, gssoc23

#573 Added Tangled Words using react.
  Contributors.md
  src/Games/TangledWords/.gitignore
  src/Games/TangledWords/README.md
  src/Games/TangledWords/package-lock.json
  src/Games/TangledWords/package.json
  src/Games/TangledWords/public/favicon.ico
  src/Games/TangledWords/public/index.html
  src/Games/TangledWords/public/logo192.png
  src/Games/TangledWords/public/logo512.png
  src/Games/TangledWords/public/manifest.json
  src/Games/TangledWords/public/robots.txt
  src/Games/TangledWords/src/App.css
  src/Games/TangledWords/src/App.js
  src/Games/TangledWords/src/App.test.js
  src/Games/TangledWords/src/components/tangled-words/tangled-words.js
  src/Games/TangledWords/src/components/tangled-words/tangled-words.sass
  src/Games/TangledWords/src/index.css
  src/Games/TangledWords/src/index.js
  src/Games/TangledWords/src/logo.svg
  src/Games/TangledWords/src/reportWebVitals.js
  src/Games/TangledWords/src/setupTests.js
  src/Games/TangledWords/yarn.lock
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
Labels: enhancement, good first issue, gssoc23, level2

#527 auto-comment.yml file is added
  .github/workflows/auto-comment.yml
Labels: enhancement, good first issue, gssoc23, level1

#592 Update data.js
  src/Homepage/Data/data.js
Labels: enhancement, level3, gssoc23

#608 Added lazy loading
  package-lock.json
  src/Routes/AllRoutes.js
  yarn.lock
Labels: gssoc23, level2

#626 Added Guess the Color game
  package-lock.json
  src/Games/GuessTheColor/App.js
  src/Games/GuessTheColor/public/index.html
  src/Games/GuessTheColor/src/ColorGame.js
  src/Games/GuessTheColor/src/guess.css
  src/Games/GuessTheColor/src/index.js
  src/Homepage/Data/data.js
  src/Routes/AllRoutes.js
  yarn.lock
Labels: hacktoberfest, gssoc23, level1
